// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmaaOEam_jDZy1Z0-SP1XsxXZWNd8kWXk',
    appId: '1:48585516771:web:1facb91dde6161d4fd87d6',
    messagingSenderId: '48585516771',
    projectId: 'musicly-ea66c',
    authDomain: 'musicly-ea66c.firebaseapp.com',
    storageBucket: 'musicly-ea66c.appspot.com',
    measurementId: 'G-831KZ03G35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4sszS-Gvc0slJiKkJx-yycKNIoaQNgEA',
    appId: '1:48585516771:android:67697d927c5cc9ecfd87d6',
    messagingSenderId: '48585516771',
    projectId: 'musicly-ea66c',
    storageBucket: 'musicly-ea66c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOXu-CuiI6LVs4_gcoOVOlXEzj2Mpg_uw',
    appId: '1:48585516771:ios:ea89f7550b4d2d24fd87d6',
    messagingSenderId: '48585516771',
    projectId: 'musicly-ea66c',
    storageBucket: 'musicly-ea66c.appspot.com',
    iosClientId: '48585516771-do6enr9qtn7rcviv0o62b39aesqs0451.apps.googleusercontent.com',
    iosBundleId: 'com.musicly',
  );
}
